# Python

In [31]:
a=2
a

2

In [32]:
type(a)

int

In [131]:
x=int(input('Please enter a number:'))
if x%2==0:
    print('x is Even')
else:
    print('x is Odd')

Please enter a number:10
x is Even


In [132]:
n=0
while n<4:
    print('Hi Reyhoon')
    n+=1

Hi Reyhoon
Hi Reyhoon
Hi Reyhoon
Hi Reyhoon


In [133]:
a='Reyhoon'
type(a)

str

In [134]:
for c in 'Reyhoon':
    print(c)

R
e
y
h
o
o
n


In [135]:
a[:3]

'Rey'

In [136]:
a[-1]

'n'

In [137]:
for i in a:
    print(i)

R
e
y
h
o
o
n


In [138]:
'n' in a

True

In [139]:
a.upper()

'REYHOON'

In [140]:
a[:3].upper()

'REY'

In [141]:
a.lower()

'reyhoon'

In [142]:
a.count('o')

2

In [143]:
b=[2,2,4,5,0]
b

[2, 2, 4, 5, 0]

In [144]:
b.count(2)

2

In [145]:
i=0
for c in 'Reyhoon':
    i=i+1
print(i)    

7


In [146]:
c=min(2,4,6,8)
c

2

In [147]:
c=max(2,4,6,8)
c

8

In [148]:
c=abs(-12.5)
c

12.5

In [149]:
import random
random.randrange(1,100,6)

73

In [150]:
range(10)

range(0, 10)

In [151]:
range(5,20,3)

range(5, 20, 3)

In [152]:
list(range(5,20,3))

[5, 8, 11, 14, 17]

In [153]:
l1=list(range(0,20,2))
l1

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [154]:
l1[:4]

[0, 2, 4, 6]

In [155]:
l1[-2]

16

In [156]:
l1[-1]

18

In [157]:
l1[-8]

4

In [158]:
type(l1)

list

In [159]:
l1[5]='Reyhoon'
l1

[0, 2, 4, 6, 8, 'Reyhoon', 12, 14, 16, 18]

In [160]:
type(l1)

list

In [161]:
ls=[str(a) for a in l1 ]
ls

['0', '2', '4', '6', '8', 'Reyhoon', '12', '14', '16', '18']

In [162]:
c=0
for i in range(7):
    c+=i
    print(c)

0
1
3
6
10
15
21


In [163]:
l=list(range(7))
sum(l)

21

In [164]:
min(l)

0

In [165]:
max(l)

6

In [166]:
l2=[True,2.0,1,'m']
l2

[True, 2.0, 1, 'm']

In [167]:
for c in l2:
    print(type(c))

<class 'bool'>
<class 'float'>
<class 'int'>
<class 'str'>


In [168]:
2==3.0

False

In [169]:
2==2*1

True

In [170]:
3>5

False

In [171]:
x=500

if x>100:
    print('x is large ')
    print(x ,' is large ')

x is large 
500  is large 


In [172]:
y=50

if y>10:
    print('y is large')
else:
    print('y is small')

y is large


In [173]:
z=-5

if z>0:
    print(z,'is posetive')
elif z<0:
    print(z,'is negative')
else:
    print(z,'is zero')


-5 is negative


In [174]:
def f(x):
    return x**2

In [175]:
f(2)

4

In [176]:
def f(x,y):
    c=x+y
    return c
print(f(1,2))

3


In [177]:
(lambda x,y: x+y)(1,2)

3

In [178]:
(lambda x,y,z: x**2+y**3+z)(2,-1,10)

13

In [179]:
a = [1, 3, 6, 7, 12, 21, 25, 50, 57]
ans=list(filter(lambda x: x%3==0 , a))
ans

[3, 6, 12, 21, 57]

In [180]:
a = [1, 3, 6, 7, 12, 21, 25, 50, 57]
ansl = []
for i in a:
    if i%3 == 0:
        ans = i
        ansl.append(ans)
        
print(ansl)

[3, 6, 12, 21, 57]


In [181]:
numbers=(2,6,4,3,9)
result=map(lambda x: x+x,numbers)
print(list(result))

[4, 12, 8, 6, 18]


In [182]:
import time
tic = time.perf_counter()
a = [1, 3, 6, 7, 12, 21, 25, 50, 57]
ansl = []
for i in a:
    if i%3 == 0:
        ans = i
        ansl.append(ans)
        
print(ansl)
toc = time.perf_counter()
timef = toc-tic
print(timef)

[3, 6, 12, 21, 57]
0.000312299991492182


In [183]:
import time
tic = time.perf_counter()
numbers=(2,6,4,3,9)
result=map(lambda x: x+x,numbers)
print(list(result))

toc = time.perf_counter()
timel = toc-tic
print(timel)

[4, 12, 8, 6, 18]
0.0002454000059515238


In [184]:
r=timef/timel
r

1.2726160713862151

In [185]:
b = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
ans=map(lambda x: 2*x-1, b)
print(list(ans))

[-1.0, -0.8, -0.6, -0.4, -0.19999999999999996, 0.0, 0.19999999999999996, 0.3999999999999999, 0.6000000000000001, 0.8, 1.0]


In [186]:
c=0
for i in range(5):
    c=c+f(i)
    print(c)

TypeError: f() missing 1 required positional argument: 'y'

In [187]:
def f(x):
    c=x**3-1
    return c

n=[1,-1,3,-3]
for i in n:
    print(f(i))

0
-2
26
-28


exp(x)

In [188]:
import math 
def exp(x,n):
    ex=0
    for i in range(n):
        ex=ex+(x**i)/(math.factorial(i))
    return ex
x=int(input('enter x:'))
n=int(input('enter n:'))
print(exp(x,n))

enter x:5
enter n:4
39.33333333333333


In [189]:
x=0

while x<10:
    x+=1
    print(x)

1
2
3
4
5
6
7
8
9
10


In [190]:
x=0

while x<10:
    x+=1
    print(x**2)

1
4
9
16
25
36
49
64
81
100


In [191]:
def inspect(x):
    if x>0:
        print(x,'is posetive')
    elif x<0:
        print(x,'is negative')
    else:
        print(x,'is zero')

In [192]:
inspect(70)

70 is posetive


In [193]:
l=list(range(21))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [194]:
for i in range(5):
    l[i]=l[i]+1
    print(l)

[1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[1, 2, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[1, 2, 3, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[1, 2, 3, 4, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [103]:
for i in range(20):
    l[i]=l[i]+1
print(l)

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 20]


In [104]:
sqr=[]
sqr.append('a')
sqr.append(2**3)
sqr.append(False)
sqr

['a', 8, False]

In [105]:
def f(x):
    return x**2
sqr=[]
for i in range(10):
    sqr.append(f(i))
sqr    

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [106]:
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
planets

['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']

In [107]:
len(planets[0])

7

In [108]:
for i in range(8):
    print(len(planets[i])) 

7
5
5
4
7
6
6
7


In [109]:
shortpl=[]
for i in range(8):
    if len(planets[i])<6:
        shortpl.append(planets[i])
print(shortpl)        

['Venus', 'Earth', 'Mars']


In [110]:
shortpl=[]
for c in planets:
    if len(c)<6:
        shortpl.append(c)
print(shortpl)  

['Venus', 'Earth', 'Mars']


In [111]:
longpl=[]
for planet in planets:
    if len(planet)>6:
        longpl.append(planet)
print(longpl)   

['Mercury', 'Jupiter', 'Neptune']


In [112]:
longpl=[planet for planet in planets if len(planet)>5 ]
longpl

['Mercury', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']

In [113]:
longpl=[a for a in planets if len(a)>6]
longpl

['Mercury', 'Jupiter', 'Neptune']

# Dictionary in Python

{-:-, -:-, -:-}

In [114]:
p2e=dict()
p2e['salllam']='hiii'
p2e['dooset daram']='love youuu'
p2e['khodafezzz']='byeee'
print(p2e)

{'salllam': 'hiii', 'dooset daram': 'love youuu', 'khodafezzz': 'byeee'}


In [115]:
p2e['salllam']

'hiii'

In [116]:
numbers={'one':1,'two':2,'three':3}
numbers

{'one': 1, 'two': 2, 'three': 3}

In [117]:
numbers['two']

2

In [118]:
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
dic_planets = {planet : planets[i][0]}

print(dic_planets)

{'Neptune': 'N'}


In [128]:
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
dic_planets={}
for i in range(len(planets)):
    dic_planets[planets[i]]=planets[i][0]
print(dic_planets)

{'Mercury': 'M', 'Venus': 'V', 'Earth': 'E', 'Mars': 'M', 'Jupiter': 'J', 'Saturn': 'S', 'Uranus': 'U', 'Neptune': 'N'}


# Numpy
Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

In [199]:
l1=list(range(10))
l1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [200]:
l2=list(range(1,30,4))
l2

[1, 5, 9, 13, 17, 21, 25, 29]

In [201]:
import numpy as np
np.array(l2)       # Create a rank 1 array

array([ 1,  5,  9, 13, 17, 21, 25, 29])

In [202]:
np.array([1,1.7,'Mahroo'])   # Create a rank 1 array

array(['1', '1.7', 'Mahroo'], dtype='<U32')

In [203]:
np.array([1,1.7,5])  # Create a rank 1 array

array([1. , 1.7, 5. ])

In [204]:
np.array(l1, dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [205]:
np.array(l1, dtype='float32')

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [206]:
x=np.array([6,7,3,9,10,1])
x

array([ 6,  7,  3,  9, 10,  1])

In [207]:
np.sort(x)

array([ 1,  3,  6,  7,  9, 10])

In [208]:
np.argsort(x)

array([5, 2, 0, 1, 3, 4], dtype=int64)

In [209]:
np.argsort([2,3,1])

array([2, 0, 1], dtype=int64)

In [210]:
np.argsort([2,0,1])

array([1, 2, 0], dtype=int64)

In [211]:
a=np.array([range(i,i+4) for i in [2,1,6]])
print((a))

[[2 3 4 5]
 [1 2 3 4]
 [6 7 8 9]]


In [212]:
a

array([[2, 3, 4, 5],
       [1, 2, 3, 4],
       [6, 7, 8, 9]])

In [213]:
a[2,3]

9

In [214]:
a[:2]

array([[2, 3, 4, 5],
       [1, 2, 3, 4]])

In [215]:
np.sort(a, axis=0)

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [6, 7, 8, 9]])

In [216]:
np.sort(a, axis=1)

array([[2, 3, 4, 5],
       [1, 2, 3, 4],
       [6, 7, 8, 9]])

In [217]:
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [218]:
np.zeros((3,3), dtype=float)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [219]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [220]:
np.full((3,4), 9.8)

array([[9.8, 9.8, 9.8, 9.8],
       [9.8, 9.8, 9.8, 9.8],
       [9.8, 9.8, 9.8, 9.8]])

In [221]:
np.arange(0,20,5)

array([ 0,  5, 10, 15])

In [222]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [223]:
np.random.random(5)

array([0.81665749, 0.75724857, 0.48204013, 0.4417272 , 0.71203565])

In [224]:
np.random.random((3,4))

array([[0.70588324, 0.29966868, 0.18513726, 0.18603809],
       [0.14150805, 0.01612103, 0.29167357, 0.93706151],
       [0.85442856, 0.22141992, 0.87761947, 0.25953832]])

In [225]:
np.random.normal(1,7,(3,4))

array([[-6.50413717,  1.18026789, -2.38665479, 12.5821009 ],
       [-4.37645376, -6.81888818,  6.87003875,  1.30036007],
       [ 5.93774871,  8.14010992, -1.2242814 , -0.0389972 ]])

In [226]:
np.random.randint(0,8,(3,3))

array([[0, 4, 2],
       [1, 6, 4],
       [1, 3, 1]])

In [227]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [228]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [229]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [230]:
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [231]:
x1=np.random.randint(10,size=6) #one-dimentional array
x1

array([8, 0, 5, 9, 1, 2])

In [232]:
x2=np.random.randint(3,10, size=(3,4))
x2

array([[7, 8, 6, 8],
       [3, 9, 4, 8],
       [4, 3, 4, 3]])

In [233]:
x3=np.random.randint(2,8, size=(2,3,2))
x3

array([[[2, 6],
        [5, 3],
        [6, 4]],

       [[4, 6],
        [2, 4],
        [4, 7]]])

In [234]:
print(x3.ndim)

3


In [235]:
print("x2 shape: ",x2.shape)

x2 shape:  (3, 4)


In [236]:
print('x3 size:', x3.size)

x3 size: 12


In [237]:
print('x3 dtype:', x3.dtype)

x3 dtype: int32


In [238]:
print("itemsize: ", x3.itemsize, "bytes")

itemsize:  4 bytes


In [239]:
print("nbytes:",  x3.nbytes, "bytes")

nbytes: 48 bytes


In [240]:
print(x2)

[[7 8 6 8]
 [3 9 4 8]
 [4 3 4 3]]


In [241]:
x2[1,:]

array([3, 9, 4, 8])

In [242]:
x2[1:3]

array([[3, 9, 4, 8],
       [4, 3, 4, 3]])

In [243]:
x2[0,1]

8

In [244]:
x2[1,-1]

8

In [245]:
x2[:,1:4:2]

array([[8, 8],
       [9, 8],
       [3, 3]])

In [246]:
x2[-1:4:2]

array([[4, 3, 4, 3]])

In [247]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [248]:
x=np.array([1,2,3])
y=np.array([3,2,1])
z=np.concatenate([y,x])
z

array([3, 2, 1, 1, 2, 3])

In [249]:
g=np.array([[1,2,3],[-1,-2,-3]])
np.concatenate([g,-g])

array([[ 1,  2,  3],
       [-1, -2, -3],
       [-1, -2, -3],
       [ 1,  2,  3]])

In [250]:
np.vstack([x,y])

array([[1, 2, 3],
       [3, 2, 1]])

In [251]:
x=np.arange(5)
x

array([0, 1, 2, 3, 4])

In [252]:
sum(x)

10

In [253]:
np.sum(x[1:3])

3

In [254]:
np.sum(x)

10

In [255]:
sum(x[1:3])

3

In [259]:
big_array = np.random.rand(100000)
%timeit sum(big_array)
%timeit np.sum(big_array)

14.8 ms ± 1.21 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
40.8 µs ± 248 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [261]:
x=np.array(range(5))
x

array([0, 1, 2, 3, 4])

In [262]:
x+5

array([5, 6, 7, 8, 9])

In [263]:
print('x+6=',x+6)

x+6= [ 6  7  8  9 10]


In [264]:
print('x**2-x=', x**2-x)

x**2-x= [ 0  0  2  6 12]


In [265]:
print('x//2=', x//2)

x//2= [0 0 1 1 2]


In [266]:
theta=np.linspace(0,np.pi,3)
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [267]:
from scipy import special
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2)   = [0.5        0.03333333 0.00909091]


In [268]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

data=np.zeros(4,dtype={'names':('name', 'age', 'weight')
                          ,'formats':('U10', 'i4', 'f8')})
data['name']=name
data['age']=age
data['weight']=weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [269]:
data[-1]

('Doug', 19, 61.5)

In [270]:
data[:3]

array([('Alice', 25, 55. ), ('Bob', 45, 85.5), ('Cathy', 37, 68. )],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [271]:
c=1
for i in range(8):
    i+=1
    c=c*i
    print(c)    

1
2
6
24
120
720
5040
40320


In [272]:
import math as mt
for i in range(9):
    print(mt.factorial(i))

1
1
2
6
24
120
720
5040
40320


In [273]:
import numpy as np
a=np.array([[1,2,3],[2,4,2],[1,1,2]])
b=np.array([[1,2,1],[3,4,1],[2,1,2]])
print(a)
print(b)
np.dot(a,b)

[[1 2 3]
 [2 4 2]
 [1 1 2]]
[[1 2 1]
 [3 4 1]
 [2 1 2]]


array([[13, 13,  9],
       [18, 22, 10],
       [ 8,  8,  6]])

In [274]:
np.multiply(a,b)

array([[ 1,  4,  3],
       [ 6, 16,  2],
       [ 2,  1,  4]])

In [275]:
np.prod(a)

192

In [276]:
q=np.multiply(a,b)
np.cumsum(q, axis=0)

array([[ 1,  4,  3],
       [ 7, 20,  5],
       [ 9, 21,  9]], dtype=int32)

In [277]:
np.cumsum(q)

array([ 1,  5,  8, 14, 30, 32, 34, 35, 39], dtype=int32)

In [278]:
np.cumsum(q, axis=1)

array([[ 1,  5,  8],
       [ 6, 22, 24],
       [ 2,  3,  7]], dtype=int32)

In [279]:
np.subtract(a,b)

array([[ 0,  0,  2],
       [-1,  0,  1],
       [-1,  0,  0]])

In [280]:
np.divide(a,b)

array([[1.        , 1.        , 3.        ],
       [0.66666667, 1.        , 2.        ],
       [0.5       , 1.        , 1.        ]])

In [281]:
np.floor_divide(a,b)

array([[1, 1, 3],
       [0, 1, 2],
       [0, 1, 1]], dtype=int32)

In [282]:
np.math.sqrt(81)

9.0

In [283]:
np.random.uniform(0,100,(3,2))

array([[31.16792437, 90.89721388],
       [95.24441577, 91.20756843],
       [92.75949092,  3.41752658]])

In [284]:
np.random.standard_normal((3,4)) #bar asase tozie normal

array([[ 0.45106535, -2.30148988, -0.26160247, -1.04634978],
       [ 0.12398873, -0.18815598, -0.80753914, -0.75545714],
       [-0.40232803,  0.14706977, -0.68126299, -2.06486144]])

In [285]:
r=np.array([[6,3,2],[9,4,5]])
m=np.logical_and(r>2,r<8)
r[m]

array([6, 3, 4, 5])

In [286]:
np.size(r)

6

In [287]:
np.shape(r)

(2, 3)

In [288]:
np.union1d(a,b) #Union

array([1, 2, 3, 4])

In [289]:
np.intersect1d(a,b) #Intersection

array([1, 2, 3, 4])

In [290]:
np.unique(b)

array([1, 2, 3, 4])

In [291]:
np.mean(a) #average

2.0

In [292]:
np.median(a) #median

2.0

In [293]:
np.std(a) #standard variation

0.9428090415820634

In [294]:
np.var(a)

0.8888888888888888

In [295]:
import math
def sin(x,n):
    sine=0
    for i in range(n):
        sign=math.pow(-1,i)
        pi=math.pi
        a=x*(pi/180)
        sine=(sine+(sign*(a**(2.0*i+1)))/math.factorial(2*i+1))
        
    return sine

In [297]:
x=int(input('enter x='))
n=int(input('enter n='))
print(sin(x,n))

enter x=90
enter n=10
1.0


# Pandas

pandas is a software library that is fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language.

In [298]:
import numpy as np
import pandas as pd

In [ ]:
np.array([1,2,3,4])

In [ ]:
help(pd)

# pd.Series

In [300]:
pd.Series([1,2,3,4])

0    1
1    2
2    3
3    4
dtype: int64

In [301]:
pd.Series([10,20,30,40] , index=['a','b','c','d'])

a    10
b    20
c    30
d    40
dtype: int64

In [302]:
data=[10,20,30,40]
s=pd.Series(data , index=['a','b','c','d'])
s

a    10
b    20
c    30
d    40
dtype: int64

In [303]:
s.values

array([10, 20, 30, 40], dtype=int64)

In [304]:
s.a

10

In [305]:
s[:'c']

a    10
b    20
c    30
dtype: int64

In [306]:
s[s>10]

b    20
c    30
d    40
dtype: int64

In [307]:
s[-1]

40

In [308]:
s[2]

30

In [309]:
s['d':]

d    40
dtype: int64

In [310]:
data=pd.Series(np.linspace(0,4,4), index=['a','b','c','d'])
data

a    0.000000
b    1.333333
c    2.666667
d    4.000000
dtype: float64

In [311]:
data=pd.Series(np.arange(0,1,0.25), index=['a','b','c','d'])
data

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [312]:
data=pd.Series(np.arange(0,1,0.25), index=[2,5,7,6])
data

2    0.00
5    0.25
7    0.50
6    0.75
dtype: float64

In [313]:
for i in data.index:
    print(i)

2
5
7
6


In [314]:
for i in data.index:
    print(i)
    print(data[i])

2
0.0
5
0.25
7
0.5
6
0.75


In [315]:
# From array:
pd.Series([1,2,3])

0    1
1    2
2    3
dtype: int64

In [316]:
# constant:
pd.Series(500,index=[11,22,33])

11    500
22    500
33    500
dtype: int64

In [317]:
# dictionary
pd.Series({1:'a',2:'b',3:'c'})

1    a
2    b
3    c
dtype: object

In [318]:
pd.Series({'1':'a','2':'b','3':'c'})

1    a
2    b
3    c
dtype: object

In [319]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area_dict

{'California': 423967,
 'Texas': 695662,
 'New York': 141297,
 'Florida': 170312,
 'Illinois': 149995}

In [320]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area=pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [321]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population=pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [322]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [323]:
'e' in data

False

In [324]:
data['a']

0.25

In [325]:
data.keys

<bound method Series.keys of a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64>

In [326]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [327]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [328]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [329]:
data['e']=1.25 # We can add an index to data

In [330]:
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [331]:
data[(data<1)&(data>0.5)]

c    0.75
dtype: float64

# Data.Frame

In [332]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area=pd.Series(area_dict)
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population=pd.Series(population_dict)

states=pd.DataFrame({'population':population,'area':area})
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [333]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [334]:
states.columns

Index(['population', 'area'], dtype='object')

In [335]:
# From a list of dictionary
data=[{'a': i , 'b' : 2*i+1} for i in range(5)]
pd.DataFrame(data)    

a  b
0  0  1
1  1  3
2  2  5
3  3  7
4  4  9

In [336]:
data=[{'a': i , 'b' : 2*i+1} for i in range(5)]
print(data)

[{'a': 0, 'b': 1}, {'a': 1, 'b': 3}, {'a': 2, 'b': 5}, {'a': 3, 'b': 7}, {'a': 4, 'b': 9}]


In [337]:
pd.Series(data)

0    {'a': 0, 'b': 1}
1    {'a': 1, 'b': 3}
2    {'a': 2, 'b': 5}
3    {'a': 3, 'b': 7}
4    {'a': 4, 'b': 9}
dtype: object

In [338]:
# It accepts the missing values 

pd.DataFrame([{'a':55 , 'b': 33},{'b': 44 , 'd' : 22}] , index=['x','y'])

a   b     d
x  55.0  33   NaN
y   NaN  44  22.0

In [339]:
pd.DataFrame({'a':55 , 'b': 33},{'c': 44 , 'd' : 22})

a   b
c  55  33
d  55  33

In [340]:
pd.DataFrame(np.random.random((3,4)), columns=['color','size','age','frame'] , index=['case1','case2','case3'])

color      size       age     frame
case1  0.639484  0.865461  0.108917  0.865903
case2  0.139171  0.682188  0.469366  0.591863
case3  0.611544  0.322527  0.738671  0.532254

In [341]:
#Structure Data
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [342]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

# Index

In [343]:
pd.Index([9,1,7,3,5])

Int64Index([9, 1, 7, 3, 5], dtype='int64')

In [344]:
ind=pd.Index([9,1,7,3,5])
ind[0]

9

In [345]:
ind[:3]

Int64Index([9, 1, 7], dtype='int64')

In [346]:
ind[1]=0  #Index does not support mutable operations it's not

TypeError: Index does not support mutable operations

In [347]:
# Many operations are possible on indeces:

indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [348]:
indA & indB  # intersection


Int64Index([3, 5, 7], dtype='int64')

In [349]:
indA | indB  # union

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [350]:
indA ^ indB  # symmetric difference

Int64Index([1, 2, 9, 11], dtype='int64')

In [351]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data=pd.DataFrame({'area':area , 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [352]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [353]:
data['pop']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: pop, dtype: int64

In [354]:
data.area is data['area']

True

In [355]:
data.pop is data['pop'] # pop is command in python.

False

In [356]:
data['density']= data['pop']/data['area']
data['density']

California     90.413926
Texas          38.018740
New York      139.076746
Florida       114.806121
Illinois       85.883763
Name: density, dtype: float64

In [357]:
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [358]:
data.values #It is a numpy array.

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [359]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [360]:
data.values[:2]

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01]])

In [361]:
data.iloc[0]  #it is a data frame

area       4.239670e+05
pop        3.833252e+07
density    9.041393e+01
Name: California, dtype: float64

In [362]:
data.iloc[:2]

area       pop    density
California  423967  38332521  90.413926
Texas       695662  26448193  38.018740

In [363]:
data.iloc[2:4]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

In [364]:
data.iloc[:3,:2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [365]:
data.loc[:'Illinois',:'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [366]:
data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [367]:
data.loc['Florida'] ['pop']

19552860.0

In [368]:
data.reset_index(drop=True)

area       pop     density
0  423967  38332521   90.413926
1  695662  26448193   38.018740
2  141297  19651127  139.076746
3  170312  19552860  114.806121
4  149995  12882135   85.883763

In [369]:
data.drop('Florida',axis=0)

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Illinois    149995  12882135   85.883763

In [370]:
data.drop('area' , axis=1)

pop     density
California  38332521   90.413926
Texas       26448193   38.018740
New York    19651127  139.076746
Florida     19552860  114.806121
Illinois    12882135   85.883763

In [371]:
data.replace({0:1})

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [372]:
import numpy as np
s1=pd.Series(np.random.randint(0,10,4),index = ['a','b','c','d'])
s1

a    5
b    8
c    4
d    5
dtype: int32

In [373]:
import pandas as pd
import numpy as np
s=pd.DataFrame(np.random.randint(0,10,(3,4)),index = ['a','b','c'],columns=['A','B','C','D'])
s

A  B  C  D
a  4  9  0  7
b  4  9  2  5
c  7  7  3  0

In [374]:
np.exp(s)

A            B          C            D
a    54.598150  8103.083928   1.000000  1096.633158
b    54.598150  8103.083928   7.389056   148.413159
c  1096.633158  1096.633158  20.085537     1.000000

In [375]:
np.sin((np.pi*s/4))

A         B         C         D
a  1.224647e-16  0.707107  0.000000 -0.707107
b  1.224647e-16  0.707107  1.000000 -0.707107
c -7.071068e-01 -0.707107  0.707107  0.000000

In [376]:
rng=np.random
data1=pd.DataFrame(np.random.randint(0,10,(2,2)), columns=list('AB'))
data1


A  B
0  4  8
1  4  0

In [377]:
data2=pd.DataFrame(np.random.randint(0,10,(2,3)), columns=list('CAB'))
data2

C  A  B
0  8  4  4
1  9  2  9

In [378]:
data1+data2

A   B   C
0  8  12 NaN
1  6   9 NaN

In [379]:
data1.add(data2)

A   B   C
0  8  12 NaN
1  6   9 NaN

In [380]:
data1.add(data2,fill_value=0)

A   B    C
0  8  12  8.0
1  6   9  9.0

In [381]:
# other operators: sub, mul, div, mod, pow
A.sub(B.iloc[0])

# Operations on Nan:
isnull() notnull() dropna() fillna()

In [390]:
data=pd.Series([np.nan, 3, 'yes', None])
data

0     NaN
1       3
2     yes
3    None
dtype: object

In [391]:
data.isnull()

0     True
1    False
2    False
3     True
dtype: bool

In [392]:
data.isnull().sum()

2

In [393]:
data[data.notnull()]

1      3
2    yes
dtype: object

In [394]:
data.dropna() #remove null rows

1      3
2    yes
dtype: object

In [395]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df.dropna()  #axis='rows'

0    1  2
1  2.0  3.0  5

In [396]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [397]:
df.fillna(0)

0    1  2
0  1.0  0.0  2
1  2.0  3.0  5
2  0.0  4.0  6

In [398]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [399]:

df.fillna(method='ffill')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  2.0  4.0  6

In [400]:

df.fillna(method='bfill')

0    1  2
0  1.0  3.0  2
1  2.0  3.0  5
2  NaN  4.0  6

In [401]:
import numpy as np
df = pd.DataFrame(np.random.rand(4, 2),
                  index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                  columns=['data1', 'data2'])
df

data1     data2
a 1  0.684949  0.635906
  2  0.632598  0.236559
b 1  0.351974  0.155368
  2  0.772837  0.081397

In [402]:
data = {('California', 2000): 33871648,
        ('California', 2010): 37253956,
        ('Texas', 2000): 20851820,
        ('Texas', 2010): 25145561,
        ('New York', 2000): 18976457,
        ('New York', 2010): 19378102}
df=pd.Series(data)
df

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

In [403]:
df.index.names = ['state', 'year']
df


state       year
California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

In [404]:
# hierarchical indices and columns
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
                                   names=['year', 'visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
                                     names=['subject', 'type'])

# mock some data
data = np.round(np.random.randn(4, 6), 1)
data[:, ::2] *= 10
data += 37

# create the DataFrame
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      25.0  36.5  43.0  36.4  40.0  37.7
     2      42.0  37.5  33.0  36.6  32.0  37.4
2014 1      46.0  36.8  28.0  36.3  38.0  35.5
     2      37.0  34.7  51.0  37.6  38.0  35.4

In [405]:
# How to call it:
health_data['Guido']

type          HR  Temp
year visit            
2013 1      43.0  36.4
     2      33.0  36.6
2014 1      28.0  36.3
     2      51.0  37.6

In [406]:
health_data['Guido']['HR'][2013,1]


43.0

In [407]:
health_data['Guido','HR'][2013,1]

43.0

In [408]:
health_data.loc[2013]

subject   Bob       Guido         Sue      
type       HR  Temp    HR  Temp    HR  Temp
visit                                      
1        25.0  36.5  43.0  36.4  40.0  37.7
2        42.0  37.5  33.0  36.6  32.0  37.4

In [409]:
health_data.loc[2013,1]

subject  type
Bob      HR      25.0
         Temp    36.5
Guido    HR      43.0
         Temp    36.4
Sue      HR      40.0
         Temp    37.7
Name: (2013, 1), dtype: float64

In [410]:
health_data[health_data>30]

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1       NaN  36.5  43.0  36.4  40.0  37.7
     2      42.0  37.5  33.0  36.6  32.0  37.4
2014 1      46.0  36.8   NaN  36.3  38.0  35.5
     2      37.0  34.7  51.0  37.6  38.0  35.4

In [411]:
data = health_data.sort_index()
data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      25.0  36.5  43.0  36.4  40.0  37.7
     2      42.0  37.5  33.0  36.6  32.0  37.4
2014 1      46.0  36.8  28.0  36.3  38.0  35.5
     2      37.0  34.7  51.0  37.6  38.0  35.4

In [412]:

data_mean = health_data.mean(level='year')
data_mean

subject   Bob        Guido          Sue       
type       HR   Temp    HR   Temp    HR   Temp
year                                          
2013     33.5  37.00  38.0  36.50  36.0  37.55
2014     41.5  35.75  39.5  36.95  38.0  35.45

In [413]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[1, 2, 3])
pd.concat([ser1, ser2])

1    A
2    B
3    C
1    D
2    E
3    F
dtype: object

In [414]:
# it can be solved by
pd.concat([ser1, ser2], ignore_index=True)

0    A
1    B
2    C
3    D
4    E
5    F
dtype: object

In [415]:
pd.concat([ser1, ser2], keys=['1', '2'])

1  1    A
   2    B
   3    C
2  1    D
   2    E
   3    F
dtype: object

In [416]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[1, 2, 3])
ser=[append(ser1).append(ser2)]


NameError: name 'append' is not defined

In [417]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
'hire_date': [2004, 2008, 2012, 2014]})
display(df1, df2)

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [418]:
df3=pd.merge(df1,df2)
df3

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [419]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
'supervisor': ['Carly', 'Guido', 'Steve']})
display(df4)
df5=pd.merge(df3, df4)
display(df5)

group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve

employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

In [420]:
df5.set_index('employee')

group  hire_date supervisor
employee                                   
Bob        Accounting       2008      Carly
Jake      Engineering       2012      Guido
Lisa      Engineering       2004      Guido
Sue                HR       2014      Steve

In [421]:
# When the dataframes do not have the overlap over all rows
df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
'food': ['fish', 'beans', 'bread']},
columns=['name', 'food'])
df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],
'drink': ['wine', 'beer']},
columns=['name', 'drink'])
display(df6, df7, pd.merge(df6, df7))


name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread

name drink
0    Mary  wine
1  Joseph  beer

name   food drink
0  Mary  bread  wine

In [422]:
pd.merge(df6, df7, how='outer') #union 

name   food drink
0   Peter   fish   NaN
1    Paul  beans   NaN
2    Mary  bread  wine
3  Joseph    NaN  beer

In [423]:
df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
'rank': [1, 2, 3, 4]})
df9 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
'rank': [3, 1, 4, 2]})

In [424]:
df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
'rank': [1, 2, 3, 4]})
df9 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
'rank': [3, 1, 4, 2]})
pd.merge(df8, df9, on="name")

name  rank_x  rank_y
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

In [425]:
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
'data': range(6)}, columns=['key', 'data'])
df

key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [426]:
df.groupby('key').sum()

data
key      
A       3
B       5
C       7

In [427]:
df.groupby('key').mean()

data
key      
A     1.5
B     2.5
C     3.5

In [428]:
df.groupby('key').max()

data
key      
A       3
B       4
C       5

In [429]:
df.groupby('key').aggregate(['min', np.median, max])

data           
     min median max
key                
A      0    1.5   3
B      1    2.5   4
C      2    3.5   5

In [430]:
df.groupby('key').transform(lambda x: x - x.mean())

data
0  -1.5
1  -1.5
2  -1.5
3   1.5
4   1.5
5   1.5

In [431]:
import seaborn as sns
titanic = sns.load_dataset('titanic')
titanic.groupby('sex')[['survived']].mean()

survived
sex             
female  0.742038
male    0.188908

In [432]:
import seaborn as sns
titanic = sns.load_dataset('titanic')
titanic.groupby('sex').mean()

survived    pclass        age     sibsp     parch       fare  \
sex                                                                    
female  0.742038  2.159236  27.915709  0.694268  0.649682  44.479818   
male    0.188908  2.389948  30.726645  0.429809  0.235702  25.523893   

        adult_male     alone  
sex                           
female    0.000000  0.401274  
male      0.930676  0.712305