# Python

In [ ]:
a=2
a

In [ ]:
type(a)

In [ ]:
x=int(input('Please enter a number:'))
if x%2==0:
    print('x is Even')
else:
    print('x is Odd')

In [ ]:
n=0
while n<4:
    print('Hi Reyhoon')
    n+=1

In [ ]:
a='Reyhoon'
type(a)

In [ ]:
for c in 'Reyhoon':
    print(c)

In [ ]:
a[:3]

In [ ]:
a[-1]

In [ ]:
for i in a:
    print(i)

In [ ]:
'n' in a

In [ ]:
a.upper()

In [ ]:
a[:3].upper()

In [ ]:
a.lower()

In [ ]:
a.count('o')

In [ ]:
b=[2,2,4,5,0]
b

In [ ]:
b.count(2)

In [ ]:
i=0
for c in 'Reyhoon':
    i=i+1
print(i)    

In [ ]:
c=min(2,4,6,8)
c

In [ ]:
c=max(2,4,6,8)
c

In [ ]:
c=abs(-12.5)
c

In [ ]:
import random
random.randrange(1,100,6)

In [ ]:
range(10)

In [ ]:
range(5,20,3)

In [ ]:
list(range(5,20,3))

In [ ]:
l1=list(range(0,20,2))
l1

In [ ]:
l1[:4]

In [ ]:
l1[-2]

In [ ]:
l1[-1]

In [ ]:
l1[-8]

In [ ]:
type(l1)

In [ ]:
l1[5]='Reyhoon'
l1

In [ ]:
type(l1)

In [ ]:
ls=[str(a) for a in l1 ]
ls

In [ ]:
c=0
for i in range(7):
    c+=i
    print(c)

In [ ]:
l=list(range(7))
sum(l)

In [ ]:
min(l)

In [ ]:
max(l)

In [ ]:
l2=[True,2.0,1,'m']
l2

In [ ]:
for c in l2:
    print(type(c))

In [ ]:
2==3.0

In [ ]:
2==2*1

In [ ]:
3>5

In [ ]:
x=500

if x>100:
    print('x is large ')
    print(x ,' is large ')

In [ ]:
y=50

if y>10:
    print('y is large')
else:
    print('y is small')

In [ ]:
z=-5

if z>0:
    print(z,'is posetive')
elif z<0:
    print(z,'is negative')
else:
    print(z,'is zero')


In [ ]:
def f(x):
    return x**2

In [ ]:
f(2)

In [ ]:
def f(x,y):
    c=x+y
    return c
print(f(1,2))

In [ ]:
(lambda x,y: x+y)(1,2)

In [ ]:
(lambda x,y,z: x**2+y**3+z)(2,-1,10)

In [ ]:
a = [1, 3, 6, 7, 12, 21, 25, 50, 57]
ans=list(filter(lambda x: x%3==0 , a))
ans

In [ ]:
a = [1, 3, 6, 7, 12, 21, 25, 50, 57]
ansl = []
for i in a:
    if i%3 == 0:
        ans = i
        ansl.append(ans)
        
print(ansl)

In [ ]:
numbers=(2,6,4,3,9)
result=map(lambda x: x+x,numbers)
print(list(result))

In [ ]:
import time
tic = time.perf_counter()
a = [1, 3, 6, 7, 12, 21, 25, 50, 57]
ansl = []
for i in a:
    if i%3 == 0:
        ans = i
        ansl.append(ans)
        
print(ansl)
toc = time.perf_counter()
timef = toc-tic
print(timef)

In [ ]:
import time
tic = time.perf_counter()
numbers=(2,6,4,3,9)
result=map(lambda x: x+x,numbers)
print(list(result))

toc = time.perf_counter()
timel = toc-tic
print(timel)

In [ ]:
r=timef/timel
r

In [ ]:
b = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
ans=map(lambda x: 2*x-1, b)
print(list(ans))

In [ ]:
for i in range(5):
    print(f(i))

In [ ]:
c=0
for i in range(5):
    c=c+f(i)
    print(c)

In [ ]:
def f(x):
    c=x**3-1
    return c

n=[1,-1,3,-3]
for i in n:
    print(f(i))

#exp(x)

In [ ]:
import math 
def exp(x,n):
    ex=0
    for i in range(n):
        ex=ex+(x**i)/(math.factorial(i))
    return ex
x=int(input('enter x:'))
n=int(input('enter n:'))
print(exp(x,n))

In [ ]:
x=0

while x<10:
    x+=1
    print(x)

In [ ]:
x=0

while x<10:
    x+=1
    print(x**2)

In [ ]:
def inspect(x):
    if x>0:
        print(x,'is posetive')
    elif x<0:
        print(x,'is negative')
    else:
        print(x,'is zero')

In [ ]:
inspect(70)

In [ ]:
l=list(range(21))
l

In [ ]:
#for i in range(20):
    l[i]=l[i]+1
    print(l)

In [ ]:
for i in range(20):
    l[i]=l[i]+1
print(l)

In [ ]:
sqr=[]
sqr.append('a')
sqr.append(2**3)
sqr.append(False)
sqr

In [ ]:
def f(x):
    return x**2
sqr=[]
for i in range(10):
    sqr.append(f(i))
sqr    

In [ ]:
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
planets

In [ ]:
len(planets[0])

In [ ]:
for i in range(8):
    print(len(planets[i])) 

In [ ]:
shortpl=[]
for i in range(8):
    if len(planets[i])<6:
        shortpl.append(planets[i])
print(shortpl)        

In [ ]:
shortpl=[]
for c in planets:
    if len(c)<6:
        shortpl.append(c)
print(shortpl)  

In [ ]:
longpl=[]
for planet in planets:
    if len(planet)>6:
        longpl.append(planet)
print(longpl)   

In [ ]:
longpl=[planet for planet in planets if len(planet)>5 ]
longpl

In [ ]:
longpl=[a for a in planets if len(a)>6]
longpl

# Dictionary in Python

{-:-, -:-, -:-}

In [ ]:
p2e=dict()
p2e['salllam']='hiii'
p2e['dooset daram']='love youuu'
p2e['khodafezzz']='byeee'
print(p2e)

In [ ]:
p2e['salllam']

In [ ]:
numbers={'one':1,'two':2,'three':3}
numbers

In [ ]:
numbers['two']

In [ ]:
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
dic_planets = {planet:planets[i][0]}

print(dic_planets)

In [ ]:
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
dic_planets={for planet in planets planet:planet[0]}
dic_planets

In [ ]:
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
dic_planets={}
for i in range(len(planets)):
    dic_planets[planets[i]]=planets[i][0]
print(dic_planets)

# Numpy

In [ ]:
l1=list(range(10))
l1

In [ ]:
l2=list(range(1,30,4))
l2

In [ ]:
import numpy as np
np.array(l2)

In [ ]:
np.array([1,1.7,'Mahroo'])

In [ ]:
np.array([1,1.7,5])

In [ ]:
np.array(l1, dtype=float)

In [ ]:
np.array(l1, dtype='float32')

In [ ]:
x=np.array([6,7,3,9,10,1])
x

In [ ]:
np.sort(x)

In [ ]:
np.argsort(x)

In [ ]:
np.argsort([2,3,1])

In [ ]:
np.argsort([2,0,1])

In [ ]:
a=np.array([range(i,i+4) for i in [2,1,6]])
print((a))

In [ ]:
a

In [ ]:
a[2,3]

In [ ]:
a[:2]

In [ ]:
np.sort(a, axis=0)

In [ ]:
np.sort(a, axis=1)

In [ ]:
np.zeros((3,4), dtype=int)

In [ ]:
np.zeros((3,3), dtype=float)

In [ ]:
np.ones(4, dtype=int)

In [ ]:
np.full((3,4), 9.8)

In [ ]:
np.arange(0,20,5)

In [ ]:
np.linspace(0,1,10)

In [ ]:
np.random.random(5)

In [ ]:
np.random.random((3,4))

In [ ]:
np.random.normal(1,7,(3,4))

In [ ]:
np.random.randint(0,8,(3,3))

In [ ]:
np.eye(3, dtype=int)

In [ ]:
np.eye(3)

In [ ]:
np.eye(3,3)

In [ ]:
np.empty((3,2))

In [ ]:
x1=np.random.randint(10,size=6) #one-dimentional array
x1

In [ ]:
x2=np.random.randint(3,10, size=(3,4))
x2

In [ ]:
x3=np.random.randint(2,8, size=(2,3,2))
x3

In [ ]:
print(x3.ndim)

In [ ]:
print("x2 shape: ",x2.shape)

In [ ]:
print('x3 size:', x3.size)

In [ ]:
print('x3 dtype:', x3.dtype)

In [ ]:
print("itemsize: ", x3.itemsize, "bytes")

In [ ]:
print("nbytes:",  x3.nbytes, "bytes")

In [ ]:
print(x2)

In [ ]:
x2[1,:]

In [ ]:
x2[1:3]

In [ ]:
x2[0,1]

In [ ]:
x2[1,-1]

In [ ]:
x2[:,1:4:2]

In [ ]:
x2[-1:4:2]

In [ ]:
np.arange(9).reshape(3,3)

In [ ]:
x=np.array([1,2,3])
y=np.array([3,2,1])
z=np.concatenate([y,x])
z

In [ ]:
g=np.array([[1,2,3],[-1,-2,-3]])
np.concatenate([g,-g])

In [ ]:
np.vstack([x,y])

In [ ]:
x=np.arange(5)
x

In [ ]:
sum(x)

In [ ]:
np.sum(x[1:3])

In [ ]:
np.sum(x)

In [ ]:
sum(x[1:3])

In [ ]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

In [ ]:
x=np.array(range(5))
x

In [ ]:
x+5

In [ ]:
print('x+6=',x+6)

In [ ]:
print('x**2-x=', x**2-x)

In [ ]:
print('x//2=', x//2)

In [ ]:
theta=np.linspace(0,np.pi,3)
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

In [ ]:
from scipy import special
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

In [ ]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

data=np.zeros(4,dtype={'names':('name', 'age', 'weight')
                          ,'formats':('U10', 'i4', 'f8')})
data['name']=name
data['age']=age
data['weight']=weight
print(data)

In [ ]:
data[-1]

In [ ]:
data[:3]

In [ ]:
c=1
for i in range(8):
    i+=1
    c=c*i
    print(c)    

In [ ]:
import math as mt
for i in range(9):
    print(mt.factorial(i))

In [12]:
import numpy as np
a=np.array([[1,2,3],[2,4,2],[1,1,2]])
b=np.array([[1,2,1],[3,4,1],[2,1,2]])
print(a)
print(b)
np.dot(a,b)

[[1 2 3]
 [2 4 2]
 [1 1 2]]
[[1 2 1]
 [3 4 1]
 [2 1 2]]


array([[13, 13,  9],
       [18, 22, 10],
       [ 8,  8,  6]])

In [11]:
np.multiply(a,b)

array([[ 1,  4,  3],
       [ 6, 16,  2],
       [ 2,  1,  4]])

In [142]:
np.prod(a)

192

In [143]:
q=np.multiply(a,b)
np.cumsum(q, axis=0)

array([[ 1,  4,  3],
       [ 7, 20,  5],
       [ 9, 21,  9]], dtype=int32)

In [144]:
np.cumsum(q)

array([ 1,  5,  8, 14, 30, 32, 34, 35, 39], dtype=int32)

In [145]:
np.cumsum(q, axis=1)

array([[ 1,  5,  8],
       [ 6, 22, 24],
       [ 2,  3,  7]], dtype=int32)

In [146]:
np.subtract(a,b)

array([[ 0,  0,  2],
       [-1,  0,  1],
       [-1,  0,  0]])

In [148]:
np.divide(a,b)

array([[1.        , 1.        , 3.        ],
       [0.66666667, 1.        , 2.        ],
       [0.5       , 1.        , 1.        ]])

In [149]:
np.floor_divide(a,b)

array([[1, 1, 3],
       [0, 1, 2],
       [0, 1, 1]], dtype=int32)

In [150]:
np.math.sqrt(81)

9.0

In [151]:
np.random.uniform(0,100,(3,2))

array([[26.90821534, 31.18852825],
       [84.13396849, 16.61110834],
       [14.62091033, 82.94651031]])

In [152]:
np.random.standard_normal((3,4)) #bar asase tozie normal

array([[ 0.16206525,  0.9459326 ,  0.94811652, -2.34270616],
       [ 0.81226176, -2.08853505,  0.31740014,  0.80740055],
       [-1.72005804,  0.08349855, -0.66441087, -0.50378107]])

In [153]:
r=np.array([[6,3,2],[9,4,5]])
m=np.logical_and(r>2,r<8)
r[m]

array([6, 3, 4, 5])

In [156]:
np.size(r)

6

In [157]:
np.shape(r)

(2, 3)

In [158]:
np.union1d(a,b) #etehaad

array([1, 2, 3, 4])

In [159]:
np.intersect1d(a,b) #eshteraak

array([1, 2, 3, 4])

In [160]:
np.unique(b)

array([1, 2, 3, 4])

In [161]:
np.mean(a) #average

2.0

In [162]:
np.median(a) #miyane

2.0

In [163]:
np.std(a) #standard variation

0.9428090415820634

In [164]:
np.var(a)

0.8888888888888888

In [168]:
import math
def sin(x,n):
    sine=0
    for i in range(n):
        sign=math.pow(-1,i)
        pi=math.pi
        a=x*(pi/180)
        sine=(sine+(sign*(a**(2.0*i+1)))/math.factorial(2*i+1))
        
    return sine

In [171]:
x=int(input('enter x='))
n=int(input('enter n='))
print(sin(x,n))

enter x=55
enter n=10
0.8191520442889918


# Pandas

In [2]:
import numpy as np
import pandas as pd

In [2]:
help(pd)

Help on package pandas:

NAME
    pandas

DESCRIPTION
    pandas - a powerful data analysis and manipulation library for Python
    
    **pandas** is a Python package providing fast, flexible, and expressive data
    structures designed to make working with "relational" or "labeled" data both
    easy and intuitive. It aims to be the fundamental high-level building block for
    doing practical, **real world** data analysis in Python. Additionally, it has
    the broader goal of becoming **the most powerful and flexible open source data
    analysis / manipulation tool available in any language**. It is already well on
    its way toward this goal.
    
    Main Features
    -------------
    Here are just a few of the things that pandas does well:
    
      - Easy handling of missing data in floating point as well as non-floating
        point data.
      - Size mutability: columns can be inserted and deleted from DataFrame and
        higher dimensional objects
      - Automatic an

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

# pd.Series

In [4]:
pd.Series([1,2,3,4])

0    1
1    2
2    3
3    4
dtype: int64

In [7]:
pd.Series([10,20,30,40] , index=['a','b','c','d'])

a    10
b    20
c    30
d    40
dtype: int64

In [11]:
data=[10,20,30,40]
s=pd.Series(data , index=['a','b','c','d'])
s

a    10
b    20
c    30
d    40
dtype: int64

In [12]:
s[:'c']

a    10
b    20
c    30
dtype: int64

In [13]:
s[-1]

40

In [14]:
s[2]

30

In [16]:
s['d':]

d    40
dtype: int64

In [21]:
data=pd.Series(np.linspace(0,4,4), index=['a','b','c','d'])
data

a    0.000000
b    1.333333
c    2.666667
d    4.000000
dtype: float64

In [22]:
data=pd.Series(np.arange(0,1,0.25), index=['a','b','c','d'])
data

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [23]:
data=pd.Series(np.arange(0,1,0.25), index=[2,5,7,6])
data

2    0.00
5    0.25
7    0.50
6    0.75
dtype: float64

In [24]:
for i in data.index:
    print(i)

2
5
7
6


In [27]:
for i in data.index:
    print(i)
    print(data[i])

2
0.0
5
0.25
7
0.5
6
0.75


In [28]:
# From array:
pd.Series([1,2,3])

0    1
1    2
2    3
dtype: int64

In [30]:
# constant:
pd.Series(500,index=[11,22,33])

11    500
22    500
33    500
dtype: int64

In [31]:
# dictionary
pd.Series({1:'a',2:'b',3:'c'})

1    a
2    b
3    c
dtype: object

In [32]:
pd.Series({'1':'a','2':'b','3':'c'})

1    a
2    b
3    c
dtype: object

In [34]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area_dict

{'California': 423967,
 'Texas': 695662,
 'New York': 141297,
 'Florida': 170312,
 'Illinois': 149995}

In [35]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area=pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [38]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population=pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [37]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [38]:
'e' in data

False

In [40]:
data['a']

0.25

In [41]:
data.keys

<bound method Series.keys of a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64>

In [42]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [43]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [46]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [47]:
data['e']=1.25 #We can add an index to data

In [48]:
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [49]:
data[(data<1)&(data>0.5)]

c    0.75
dtype: float64

# Data.Frame

In [40]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area=pd.Series(area_dict)
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population=pd.Series(population_dict)

states=pd.DataFrame({'population':population,'area':area})
data

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [41]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [44]:
states.columns

Index(['population', 'area'], dtype='object')

In [11]:
# From a list of dictionary
data=[{'a': i , 'b' : 2*i+1} for i in range(5)]
pd.DataFrame(data)    

a  b
0  0  1
1  1  3
2  2  5
3  3  7
4  4  9

In [12]:
data=[{'a': i , 'b' : 2*i+1} for i in range(5)]
print(data)

[{'a': 0, 'b': 1}, {'a': 1, 'b': 3}, {'a': 2, 'b': 5}, {'a': 3, 'b': 7}, {'a': 4, 'b': 9}]


In [13]:
pd.Series(data)

0    {'a': 0, 'b': 1}
1    {'a': 1, 'b': 3}
2    {'a': 2, 'b': 5}
3    {'a': 3, 'b': 7}
4    {'a': 4, 'b': 9}
dtype: object

In [19]:
# It accepts the missing values 

pd.DataFrame([{'a':55 , 'b': 33},{'b': 44 , 'd' : 22}] , index=['x','y'])

a   b     d
x  55.0  33   NaN
y   NaN  44  22.0

In [17]:
pd.DataFrame({'a':55 , 'b': 33},{'c': 44 , 'd' : 22})

a   b
c  55  33
d  55  33

In [21]:
pd.DataFrame(np.random.random((3,4)), columns=['color','size','age','frame'] , index=['case1','case2','case3'])

color      size       age     frame
case1  0.780066  0.878470  0.438322  0.096903
case2  0.373309  0.648464  0.878313  0.149567
case3  0.501937  0.888047  0.384775  0.888819

In [22]:
#Structure Data
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [23]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

# Index

In [25]:
pd.Index([9,1,7,3,5])

Int64Index([9, 1, 7, 3, 5], dtype='int64')

In [26]:
ind=pd.Index([9,1,7,3,5])
ind[0]

9

In [28]:
ind[:3]

Int64Index([9, 1, 7], dtype='int64')

In [ ]:
ind[1]=0  #Index does not support mutable operations it's not

In [31]:
# Many operations are possible on indeces:

indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [32]:
indA & indB  # intersection


Int64Index([3, 5, 7], dtype='int64')

In [33]:
indA | indB  # union

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [35]:
indA ^ indB  # symmetric difference

Int64Index([1, 2, 9, 11], dtype='int64')

In [56]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data=pd.DataFrame({'area':area , 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [57]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [59]:
data['pop']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: pop, dtype: int64

In [60]:
data.area is data['area']

True

In [61]:
data.pop is data['pop'] # pop is command in python.

False

In [63]:
data['density']= data['pop']/data['area']
data['density']

California     90.413926
Texas          38.018740
New York      139.076746
Florida       114.806121
Illinois       85.883763
Name: density, dtype: float64

In [64]:
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [65]:
data.values #It is a numpy array.

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [66]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [67]:
data.values[:2]

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01]])

In [69]:
data.iloc[0]  #it is a data frame

area       4.239670e+05
pop        3.833252e+07
density    9.041393e+01
Name: California, dtype: float64

In [70]:
data.iloc[:2]

area       pop    density
California  423967  38332521  90.413926
Texas       695662  26448193  38.018740

In [75]:
data.iloc[2:4]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

In [76]:
data.iloc[:3,:2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [78]:
data.loc[:'Illinois',:'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [79]:
data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [80]:
import numpy as np
s1=pd.Series(np.random.randint(0,10,4),index = ['a','b','c','d'])
s1

a    5
b    1
c    0
d    5
dtype: int32

In [81]:
import pandas as pd
import numpy as np
s=pd.DataFrame(np.random.randint(0,10,(3,4)),index = ['a','b','c'],columns=['A','B','C','D'])
s

A  B  C  D
a  6  8  1  5
b  2  4  3  1
c  4  4  3  5

In [82]:
np.exp(s)

A            B          C           D
a  403.428793  2980.957987   2.718282  148.413159
b    7.389056    54.598150  20.085537    2.718282
c   54.598150    54.598150  20.085537  148.413159

In [83]:
np.sin((np.pi*s/4))

A             B         C         D
a -1.000000e+00 -2.449294e-16  0.707107 -0.707107
b  1.000000e+00  1.224647e-16  0.707107  0.707107
c  1.224647e-16  1.224647e-16  0.707107 -0.707107

In [96]:
rng=np.random
data1=pd.DataFrame(np.random.randint(0,10,(2,2)), columns=list('AB'))
data1


A  B
0  8  7
1  9  7

In [99]:
data2=pd.DataFrame(np.random.randint(0,10,(2,3)), columns=list('CAB'))
data2

C  A  B
0  2  5  0
1  7  1  0

In [100]:
data1+data2

A  B   C
0  13  7 NaN
1  10  7 NaN

In [101]:
data1.add(data2)

A  B   C
0  13  7 NaN
1  10  7 NaN

In [102]:
data1.add(data2,fill_value=0)

A  B    C
0  13  7  2.0
1  10  7  7.0

In [103]:
# other operators: sub, mul, div, mod, pow 

In [104]:
A.sub(B.iloc[0])

A  B   C
0  2  5 NaN
1 -6  2 NaN

# Operations on Nan:
isnull() notnull() dropna() fillna()

In [106]:
data=pd.Series([np.nan, 3, 'yes', None])
data

0     NaN
1       3
2     yes
3    None
dtype: object

In [108]:
data.isnull()

0     True
1    False
2    False
3     True
dtype: bool

In [110]:
data.isnull().sum()

2

In [112]:
data[data.notnull()]

1      3
2    yes
dtype: object

In [114]:
data.dropna() #remove null rows

1      3
2    yes
dtype: object

In [120]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df.dropna()  #axis='rows'

0    1  2
1  2.0  3.0  5

In [117]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [121]:
df.fillna(0)

0    1  2
0  1.0  0.0  2
1  2.0  3.0  5
2  0.0  4.0  6

In [122]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [123]:

df.fillna(method='ffill')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  2.0  4.0  6

In [124]:

df.fillna(method='bfill')

0    1  2
0  1.0  3.0  2
1  2.0  3.0  5
2  NaN  4.0  6

In [67]:
import numpy as np
df = pd.DataFrame(np.random.rand(4, 2),
                  index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                  columns=['data1', 'data2'])
df

data1     data2
a 1  0.687507  0.334945
  2  0.144799  0.709821
b 1  0.982586  0.383580
  2  0.207343  0.733972

In [68]:
data = {('California', 2000): 33871648,
        ('California', 2010): 37253956,
        ('Texas', 2000): 20851820,
        ('Texas', 2010): 25145561,
        ('New York', 2000): 18976457,
        ('New York', 2010): 19378102}
df=pd.Series(data)
df

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

In [69]:
df.index.names = ['state', 'year']
df


state       year
California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

In [70]:
# hierarchical indices and columns
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
                                   names=['year', 'visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
                                     names=['subject', 'type'])

# mock some data
data = np.round(np.random.randn(4, 6), 1)
data[:, ::2] *= 10
data += 37

# create the DataFrame
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      36.0  35.2  24.0  37.6  30.0  37.7
     2      45.0  36.3  44.0  37.6  47.0  38.9
2014 1      42.0  36.7  37.0  38.0  21.0  38.8
     2      50.0  36.7  38.0  37.2  46.0  36.0

In [71]:
# How to call it:
health_data['Guido']

type          HR  Temp
year visit            
2013 1      24.0  37.6
     2      44.0  37.6
2014 1      37.0  38.0
     2      38.0  37.2

In [72]:
health_data['Guido']['HR'][2013,1]


24.0

In [73]:
health_data['Guido','HR'][2013,1]

24.0

In [74]:
health_data.loc[2013]

subject   Bob       Guido         Sue      
type       HR  Temp    HR  Temp    HR  Temp
visit                                      
1        36.0  35.2  24.0  37.6  30.0  37.7
2        45.0  36.3  44.0  37.6  47.0  38.9

In [75]:
health_data.loc[2013,1]

subject  type
Bob      HR      36.0
         Temp    35.2
Guido    HR      24.0
         Temp    37.6
Sue      HR      30.0
         Temp    37.7
Name: (2013, 1), dtype: float64

In [76]:
health_data[health_data>30]

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      36.0  35.2   NaN  37.6   NaN  37.7
     2      45.0  36.3  44.0  37.6  47.0  38.9
2014 1      42.0  36.7  37.0  38.0   NaN  38.8
     2      50.0  36.7  38.0  37.2  46.0  36.0

In [77]:
data = health_data.sort_index()
data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      36.0  35.2  24.0  37.6  30.0  37.7
     2      45.0  36.3  44.0  37.6  47.0  38.9
2014 1      42.0  36.7  37.0  38.0  21.0  38.8
     2      50.0  36.7  38.0  37.2  46.0  36.0

In [78]:

data_mean = health_data.mean(level='year')
data_mean

subject   Bob        Guido         Sue      
type       HR   Temp    HR  Temp    HR  Temp
year                                        
2013     40.5  35.75  34.0  37.6  38.5  38.3
2014     46.0  36.70  37.5  37.6  33.5  37.4

In [79]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[1, 2, 3])
pd.concat([ser1, ser2])

1    A
2    B
3    C
1    D
2    E
3    F
dtype: object

In [80]:
# it can be solved by
pd.concat([ser1, ser2], ignore_index=True)

0    A
1    B
2    C
3    D
4    E
5    F
dtype: object

In [81]:
pd.concat([ser1, ser2], keys=['1', '2'])

1  1    A
   2    B
   3    C
2  1    D
   2    E
   3    F
dtype: object

In [82]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[1, 2, 3])
ser=[append(ser1).append(ser2)]


NameError: name 'append' is not defined

In [83]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
'hire_date': [2004, 2008, 2012, 2014]})
display(df1, df2)

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [84]:
df3=pd.merge(df1,df2)
df3

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [85]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
'supervisor': ['Carly', 'Guido', 'Steve']})
display(df4)
df5=pd.merge(df3, df4)
display(df5)

group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve

employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

In [86]:
df5.set_index('employee')

group  hire_date supervisor
employee                                   
Bob        Accounting       2008      Carly
Jake      Engineering       2012      Guido
Lisa      Engineering       2004      Guido
Sue                HR       2014      Steve

In [87]:
# When the dataframes do not have the overlap over all rows
df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
'food': ['fish', 'beans', 'bread']},
columns=['name', 'food'])
df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],
'drink': ['wine', 'beer']},
columns=['name', 'drink'])
display(df6, df7, pd.merge(df6, df7))


name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread

name drink
0    Mary  wine
1  Joseph  beer

name   food drink
0  Mary  bread  wine

In [88]:
pd.merge(df6, df7, how='outer') #اجتماع 

name   food drink
0   Peter   fish   NaN
1    Paul  beans   NaN
2    Mary  bread  wine
3  Joseph    NaN  beer

In [89]:
df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
'rank': [1, 2, 3, 4]})
df9 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
'rank': [3, 1, 4, 2]})

In [90]:
df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
'rank': [1, 2, 3, 4]})
df9 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
'rank': [3, 1, 4, 2]})
pd.merge(df8, df9, on="name")

name  rank_x  rank_y
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

In [91]:
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
'data': range(6)}, columns=['key', 'data'])
df

key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [92]:
df.groupby('key').sum()

data
key      
A       3
B       5
C       7

In [93]:
df.groupby('key').mean()

data
key      
A     1.5
B     2.5
C     3.5

In [94]:
df.groupby('key').max()

data
key      
A       3
B       4
C       5

In [95]:
df.groupby('key').aggregate(['min', np.median, max])

data           
     min median max
key                
A      0    1.5   3
B      1    2.5   4
C      2    3.5   5

In [96]:
df.groupby('key').transform(lambda x: x - x.mean())

data
0  -1.5
1  -1.5
2  -1.5
3   1.5
4   1.5
5   1.5

In [97]:
import seaborn as sns
titanic = sns.load_dataset('titanic')
titanic.groupby('sex')[['survived']].mean()

survived
sex             
female  0.742038
male    0.188908

In [98]:
import seaborn as sns
titanic = sns.load_dataset('titanic')
titanic.groupby('sex').mean()

survived    pclass        age     sibsp     parch       fare  \
sex                                                                    
female  0.742038  2.159236  27.915709  0.694268  0.649682  44.479818   
male    0.188908  2.389948  30.726645  0.429809  0.235702  25.523893   

        adult_male     alone  
sex                           
female    0.000000  0.401274  
male      0.930676  0.712305